# Generated by Django 3.1.4 on 2021-04-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20210425_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='noindex',
            field=models.BooleanField(default=False),
        ),
    ]
