# Generated by Django 3.1.4 on 2021-03-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='prevent_booking_after_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
