# Generated by Django 3.1.4 on 2021-03-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_bookingsettings_prevent_booking_after_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingsettings',
            old_name='accept_bookings_within_days',
            new_name='prement_bookings_after_days',
        ),
        migrations.RenameField(
            model_name='bookingsettings',
            old_name='prevent_booking_after_date',
            new_name='prevent_bookings_after_date',
        ),
    ]
