# Generated by Django 3.1.4 on 2021-03-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_auto_20210306_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingsettings',
            old_name='prement_bookings_after_days',
            new_name='prevent_bookings_after_days',
        ),
    ]
