# Generated by Django 3.1.4 on 2021-06-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_bookingsettings_slot_buffer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsettings',
            name='prevent_bookings_after_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
