# Generated by Django 3.2.10 on 2022-05-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_bookingsettings_booking_notification_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='incentive_discount_adjacent_slots',
            field=models.IntegerField(default=0, help_text='Amount in EUR for the discount to be applied to slots close to other taken slots'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='incentive_discount_parallel_slots',
            field=models.IntegerField(default=0, help_text='Amount in EUR for the discount to be applied to slots nexnextt to other taken slots'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='booking_notification_emails',
            field=models.CharField(blank=True, help_text='Separate emails with a comma ","', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='prevent_bookings_after_date',
            field=models.DateField(blank=True, help_text='Any slots after this date will not show in the calendar', null=True),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='slot_buffer_time',
            field=models.IntegerField(blank=True, default=60, help_text='Buffer time in minutes', null=True),
        ),
    ]
