# Generated by Django 3.1.4 on 2021-03-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='link_title_de',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='link_title_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
