# Generated by Django 3.1.4 on 2021-03-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20210306_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='open_in_new_tab',
            new_name='new_tab',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='noopener',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
