# Generated by Django 3.1.4 on 2021-03-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('menus', '0006_coupondocument_docs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CouponDocument',
            new_name='Document',
        ),
        migrations.RenameModel(
            old_name='CouponTemplate',
            new_name='DocumentCollection',
        ),
    ]
