# Generated by Django 3.1.4 on 2021-03-25 18:33

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_auto_20210325_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name_de',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='name_en',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='docs',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='menus.documentcollection'),
        ),
    ]
