# Generated by Django 3.1.4 on 2021-04-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_auto_20210325_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='WagtailLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=8, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'wagtail_language',
                'verbose_name_plural': 'wagtail_languages',
            },
        ),
    ]
