# Generated by Django 3.1.4 on 2021-04-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_wagtaillanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagtaillanguage',
            name='language_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='wagtaillanguage',
            name='svg_flag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
