# Generated by Django 3.1.4 on 2021-03-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210306_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='name_de',
            field=models.CharField(max_length=32, null=True, verbose_name='display name'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='name_en',
            field=models.CharField(max_length=32, null=True, verbose_name='display name'),
        ),
    ]
