# Generated by Django 3.1.4 on 2021-03-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210306_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_de',
            field=models.CharField(max_length=32, null=True, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=32, null=True, verbose_name='Product'),
        ),
    ]
