# Generated by Django 3.1.4 on 2021-03-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210306_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='is_apply_to_basket',
            field=models.BooleanField(default=False, verbose_name='entire basket'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_individual_use',
            field=models.BooleanField(default=True, verbose_name='can be combined'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_overrule_individual_use',
            field=models.BooleanField(default=False, verbose_name='can be combined'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_percent',
            field=models.BooleanField(default=False, verbose_name='is percent'),
        ),
    ]
