# Generated by Django 3.1.4 on 2021-03-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20210307_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='booking.productfamily', verbose_name='Family'),
        ),
    ]
