# Generated by Django 3.1.4 on 2021-04-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20210320_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='erstellt'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Erstellt'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='email',
            field=models.EmailField(max_length=128, verbose_name='E-Mail-Adresse'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Anzeigename'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name_de',
            field=models.CharField(max_length=32, null=True, verbose_name='Anzeigename'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name_en',
            field=models.CharField(max_length=32, null=True, verbose_name='Anzeigename'),
        ),
        migrations.AlterField(
            model_name='product',
            name='players',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Spieler'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/rooms', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='room',
            name='photo_alt',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Alternativtext'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='duration',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Zeitspanne'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='duration',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Zeitspanne'),
        ),
    ]
