# Generated by Django 3.1.4 on 2021-04-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20210423_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
