# Generated by Django 3.1.4 on 2021-06-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_slot_is_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='reference'),
        ),
    ]
