# Generated by Django 3.1.4 on 2021-12-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20210622_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='players',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Players'),
        ),
    ]
