# Generated by Django 3.2.10 on 2021-12-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20211213_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name=''),
        ),
    ]
