# Generated by Django 3.2.10 on 2022-02-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20220215_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_selectable',
            field=models.BooleanField(default=True, verbose_name='Is selectable in calendar'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_individual_use',
            field=models.BooleanField(default=True, verbose_name="can't be combined"),
        ),
    ]
