# Generated by Django 3.2.10 on 2022-02-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20220218_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='upgrade',
        ),
        migrations.AddField(
            model_name='product',
            name='upgrade_price',
            field=models.DecimalField(decimal_places=2, default=120.0, max_digits=8, verbose_name='Upgrade Price'),
        ),
    ]
