# Generated by Django 3.2.10 on 2022-05-30 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_auto_20220526_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='booking.slot', verbose_name='slot'),
        ),
    ]
