# Generated by Django 3.1.4 on 2021-03-14 14:54

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210307_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='group_offers',
            field=wagtail.core.fields.StreamField([('offers', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add a title for the cards if necessary, ', required=False)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Use a 400x300px picture,', required=True)), ('name', wagtail.core.blocks.CharBlock(max_length=48)), ('position', wagtail.core.blocks.TextBlock(max_length=48)), ('text', wagtail.core.blocks.TextBlock(max_length=256, required=False))])))]))], blank=True, null=True),
        ),
    ]
