# Generated by Django 3.1.4 on 2021-03-14 15:46

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_group_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='group_offers',
            field=wagtail.core.fields.StreamField([('offers', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([])))]))], blank=True, null=True),
        ),
    ]
