# Generated by Django 3.1.4 on 2021-03-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210314_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='our_rooms_header',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
