# Generated by Django 3.1.4 on 2021-03-17 17:49

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_homepage_our_rooms_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='our_rooms_header_de',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='our_rooms_header_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='our_rooms_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='our_rooms_text_de',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='our_rooms_text_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
