# Generated by Django 3.1.4 on 2021-03-18 14:16

import apps.wagtail.streams.blocks
from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_roompage_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='roompage',
            name='video',
            field=wagtail.core.fields.StreamField([('video', apps.wagtail.streams.blocks.MyMapsBlock())], null=True),
        ),
    ]
