# Generated by Django 3.1.4 on 2021-03-18 14:52

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_roompage_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roompage',
            name='gallery',
            field=wagtail.core.fields.StreamField([('gallery', wagtail.core.blocks.StructBlock([('gallery', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())])))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roompage',
            name='video',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
