# Generated by Django 3.1.4 on 2021-03-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210318_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roompage',
            name='gallery',
        ),
    ]
