# Generated by Django 3.1.4 on 2021-03-18 15:09

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_roompage_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='roompage',
            name='gallery',
            field=wagtail.core.fields.StreamField([('gallery', wagtail.core.blocks.StructBlock([('gallery', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))]))], blank=True, null=True),
        ),
    ]
