# Generated by Django 3.1.4 on 2021-03-21 16:26

from django.db import migrations
import django.db.models.query
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20210321_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booknowpage',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='booknowpage',
            name='header_image_alt',
        ),
        migrations.RemoveField(
            model_name='booknowpage',
            name='header_image_alt_de',
        ),
        migrations.RemoveField(
            model_name='booknowpage',
            name='header_image_alt_en',
        ),
        migrations.RemoveField(
            model_name='booknowpage',
            name='seo_image',
        ),
        migrations.RemoveField(
            model_name='booknowpage',
            name='seo_image_alt',
        ),
        migrations.RemoveField(
            model_name='booknowpage',
            name='seo_image_alt_de',
        ),
        migrations.RemoveField(
            model_name='booknowpage',
            name='seo_image_alt_en',
        ),
        migrations.RemoveField(
            model_name='couponspage',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='couponspage',
            name='header_image_alt',
        ),
        migrations.RemoveField(
            model_name='couponspage',
            name='header_image_alt_de',
        ),
        migrations.RemoveField(
            model_name='couponspage',
            name='header_image_alt_en',
        ),
        migrations.RemoveField(
            model_name='couponspage',
            name='seo_image',
        ),
        migrations.RemoveField(
            model_name='couponspage',
            name='seo_image_alt',
        ),
        migrations.RemoveField(
            model_name='couponspage',
            name='seo_image_alt_de',
        ),
        migrations.RemoveField(
            model_name='couponspage',
            name='seo_image_alt_en',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='reviews',
            field=wagtail.core.fields.StreamField([('review_family', wagtail.core.blocks.MultipleChoiceBlock(choices=django.db.models.query.QuerySet.values_list))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='reviews_de',
            field=wagtail.core.fields.StreamField([('review_family', wagtail.core.blocks.MultipleChoiceBlock(choices=django.db.models.query.QuerySet.values_list))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='reviews_en',
            field=wagtail.core.fields.StreamField([('review_family', wagtail.core.blocks.MultipleChoiceBlock(choices=django.db.models.query.QuerySet.values_list))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roompage',
            name='reviews',
            field=wagtail.core.fields.StreamField([('review_family', wagtail.core.blocks.MultipleChoiceBlock(choices=django.db.models.query.QuerySet.values_list))], blank=True, null=True),
        ),
    ]
