# Generated by Django 3.1.4 on 2021-04-22 11:31

from django.db import migrations
import django.db.models.query
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_wagtaillanguage'),
        ('home', '0075_auto_20210422_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknowpage',
            name='translations',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='menus.WagtailLanguage'),
        ),
        migrations.AddField(
            model_name='cookiesettingspage',
            name='translations',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='menus.WagtailLanguage'),
        ),
        migrations.AddField(
            model_name='couponspage',
            name='translations',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='menus.WagtailLanguage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='translations',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='menus.WagtailLanguage'),
        ),
        migrations.AddField(
            model_name='roompage',
            name='translations',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='menus.WagtailLanguage'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='reviews',
            field=wagtail.core.fields.StreamField([('review_family', wagtail.core.blocks.MultipleChoiceBlock(choices=django.db.models.query.QuerySet.values_list))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='reviews_de',
            field=wagtail.core.fields.StreamField([('review_family', wagtail.core.blocks.MultipleChoiceBlock(choices=django.db.models.query.QuerySet.values_list))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='reviews_en',
            field=wagtail.core.fields.StreamField([('review_family', wagtail.core.blocks.MultipleChoiceBlock(choices=django.db.models.query.QuerySet.values_list))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roompage',
            name='reviews',
            field=wagtail.core.fields.StreamField([('review_family', wagtail.core.blocks.MultipleChoiceBlock(choices=django.db.models.query.QuerySet.values_list))], blank=True, null=True),
        ),
    ]
