# Generated by Django 3.1.4 on 2021-03-21 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('flex', '0003_auto_20210314_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='extra_schema',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='header_image_alt',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='header_image_alt_de',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='header_image_alt_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='seo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Seo Image'),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='seo_image_alt',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='seo_image_alt_de',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='seo_image_alt_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='infopage',
            name='extra_schema',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infopage',
            name='header_image_alt',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='infopage',
            name='header_image_alt_de',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='infopage',
            name='header_image_alt_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='infopage',
            name='seo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Seo Image'),
        ),
        migrations.AddField(
            model_name='infopage',
            name='seo_image_alt',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='infopage',
            name='seo_image_alt_de',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='infopage',
            name='seo_image_alt_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
