# Generated by Django 3.1.4 on 2021-03-21 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('flex', '0004_auto_20210321_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Header Image'),
        ),
    ]
