# Generated by Django 3.1.4 on 2021-03-21 19:09

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0007_auto_20210321_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='subject_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='subject_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='thank_you_text_de',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='thank_you_text_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
