# Generated by Django 3.1.4 on 2021-03-22 19:06

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0009_auto_20210322_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='submitted_text_de',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='submitted_text_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='submitted_title_de',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='submitted title'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='submitted_title_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='submitted title'),
        ),
    ]
