# Generated by Django 3.1.4 on 2021-04-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0018_auto_20210422_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='help_text_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='help text'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='help_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='help text'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='label_de',
            field=models.CharField(help_text='The label of the form field', max_length=255, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='label_en',
            field=models.CharField(help_text='The label of the form field', max_length=255, null=True, verbose_name='label'),
        ),
    ]
