# Generated by Django 3.1.4 on 2021-04-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0019_auto_20210422_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formpage',
            name='noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='infopage',
            name='noindex',
            field=models.BooleanField(default=False),
        ),
    ]
