# Generated by Django 3.1.4 on 2021-03-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0003_auto_20210319_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewfamily',
            options={'verbose_name': 'Review Family', 'verbose_name_plural': 'Review Families'},
        ),
        migrations.AddField(
            model_name='review',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Platform'),
        ),
    ]
