# Generated by Django 3.1.4 on 2021-03-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_auto_20210319_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPaltform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'ReviewPaltform',
                'verbose_name_plural': 'ReviewPaltforms',
            },
        ),
        migrations.RemoveField(
            model_name='review',
            name='platform',
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
    ]
