# Generated by Django 3.1.4 on 2021-03-19 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_auto_20210319_1116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewPaltform',
            new_name='ReviewPlatform',
        ),
    ]
