# Generated by Django 3.1.4 on 2021-03-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0007_review_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewplatform',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Score'),
        ),
    ]
