# Generated by Django 3.1.4 on 2021-03-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0008_reviewplatform_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewplatform',
            name='link',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Link'),
        ),
    ]
