# Generated by Django 3.1.4 on 2021-03-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0009_reviewplatform_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewplatform',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewplatform',
            name='star_icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
